[log]
path = "logs"
format = "log_%(date)s-%(time)s.txt"
level = 1
enabled = false

[net]
tickrate = 29
port = 1212
bindto = "::,0.0.0.0"
max_connections = 60

[status]
enabled = true

[game]
hostname = "[RU][MRP] Ã— Space Cats \U0001F30C - ĞœÑ‹ Ğ¾Ğ±Ğ½Ğ¾Ğ²Ğ¸Ğ»Ğ¸ÑÑŒ!"
desc = """
ğŸŒŸ Space Cats â€” Ğ½Ğ¾Ğ²Ñ‹Ğ¹ ÑĞµÑ€Ğ²ĞµÑ€, ÑĞ¾Ğ·Ğ´Ğ°Ğ½Ğ½Ñ‹Ğ¹ Ğ½Ğ° Ğ¾ÑĞ½Ğ¾Ğ²Ğµ Ğ±Ğ¸Ğ»Ğ´Ğ° Backmen, Ğ³Ğ´Ğµ Ğ»Ğ°Ğ¹Ñ‚-Ğ¼ĞµĞ´Ğ¸ÑƒĞ¼ Ğ¾Ñ‚Ñ‹Ğ³Ñ€Ñ‹Ñˆ ÑĞ¾Ñ‡ĞµÑ‚Ğ°ÑÑ‚ÑÑ Ñ ÑƒĞ²Ğ»ĞµĞºĞ°Ñ‚ĞµĞ»ÑŒĞ½Ñ‹Ğ¼ Ğ¸Ğ³Ñ€Ğ¾Ğ²Ñ‹Ğ¼ Ğ¿Ñ€Ğ¾Ñ†ĞµÑÑĞ¾Ğ¼.
Ğ¡ĞµĞ¹Ñ‡Ğ°Ñ Ğ¼Ñ‹ Ğ°ĞºÑ‚Ğ¸Ğ²Ğ½Ğ¾ Ğ½Ğ°Ğ±Ğ¸Ñ€Ğ°ĞµĞ¼ Ğ½Ğ¾Ğ²Ñ‹Ñ… Ğ°Ğ´Ğ¼Ğ¸Ğ½Ğ¸ÑÑ‚Ñ€Ğ°Ñ‚Ğ¾Ñ€Ğ¾Ğ² Ğ¸ Ñ€Ğ°Ğ·Ñ€Ğ°Ğ±Ğ¾Ñ‚Ñ‡Ğ¸ĞºĞ¾Ğ². ĞŸÑ€Ğ¸ÑĞ¾ĞµĞ´Ğ¸Ğ½ÑĞ¹Ñ‚ĞµÑÑŒ Ğº Ğ½Ğ°Ğ¼ Ğ¸ ÑÑ‚Ğ°Ğ½ÑŒÑ‚Ğµ Ñ‡Ğ°ÑÑ‚ÑŒÑ Ğ½Ğ°ÑˆĞµĞ³Ğ¾ ÑƒĞ½Ğ¸ĞºĞ°Ğ»ÑŒĞ½Ğ¾Ğ³Ğ¾ Ğ¿Ñ€Ğ¾ĞµĞºÑ‚Ğ°!
â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€
ğŸ“š â”‹ ĞÑ‚ĞºÑ€Ñ‹Ñ‚Ñ‹Ğ¹ ÑĞµÑ€Ğ²ĞµÑ€ Ñ Ğ´Ñ€ÑƒĞ¶ĞµĞ»ÑĞ±Ğ½Ñ‹Ğ¼Ğ¸ Ñ‚Ñ€ĞµĞ±Ğ¾Ğ²Ğ°Ğ½Ğ¸ÑĞ¼Ğ¸ Ğº Ñ€Ğ¾Ğ»ĞµĞ²Ğ¾Ğ¼Ñƒ Ğ¾Ñ‚Ñ‹Ğ³Ñ€Ñ‹ÑˆÑƒ, Ğ»Ğ°Ğ¹Ñ‚-Ğ¼ĞµĞ´Ğ¸ÑƒĞ¼.
ğŸš€ â”‹ Ğ ĞµĞ¶Ğ¸Ğ¼ Ğ±Ğ¾Ñ Ğ½Ğ° Ğ±Ğ°Ñ€Ğ¶Ğ°Ñ… â€” ÑĞ¿Ğ¸Ñ‡ĞµÑĞºĞ¸Ğµ ĞºĞ¾ÑĞ¼Ğ¸Ñ‡ĞµÑĞºĞ¸Ğµ ÑÑ€Ğ°Ğ¶ĞµĞ½Ğ¸Ñ Ğ¶Ğ´ÑƒÑ‚ Ğ²Ğ°Ñ!
ğŸ‘» â”‹ Ğ’ÑÑ‚Ñ€ĞµÑ‡Ğ°Ğ¹Ñ‚Ğµ Ğ½Ğ¾Ğ²Ñ‹Ñ… Ğ°Ğ½Ñ‚Ğ°Ğ³Ğ¾Ğ½Ğ¸ÑÑ‚Ğ¾Ğ²: Ğ‘Ğ»Ğ¾Ğ±, ĞºÑƒĞ»ÑŒÑ‚Ğ¸ÑÑ‚Ñ‹ Ğ¿Ğ»Ğ¾Ñ‚Ğ¸, Ğ·Ğ»Ñ‹Ğµ Ğ±Ğ»Ğ¸Ğ·Ğ½ĞµÑ†Ñ‹ Ğ¸ Ğ´Ñ€ÑƒĞ³Ğ¸Ğµ!
ğŸ  â”‹ Ğ¦ĞµĞ½Ñ‚ĞšĞ¾Ğ¼Ğ¼ Ñ‚ĞµĞ¿ĞµÑ€ÑŒ Ğ´Ğ¾ÑÑ‚ÑƒĞ¿ĞµĞ½ Ğ´Ğ»Ñ Ğ¸Ğ³Ñ€Ğ¾ĞºĞ¾Ğ². Ğ’ĞµÑ€ÑˆĞ¸Ñ‚Ğµ ÑĞ»Ğ°Ğ²Ñƒ NanoTrasen!
ğŸ’° â”‹ Ğ­ĞºĞ¾Ğ½Ğ¾Ğ¼Ğ¸Ñ‡ĞµÑĞºĞ°Ñ ÑĞ¸ÑÑ‚ĞµĞ¼Ğ°: Ğ·Ğ°Ñ€Ğ°Ğ±Ğ¾Ñ‚Ğ½Ñ‹Ğµ Ğ¿Ğ»Ğ°Ñ‚Ñ‹ Ğ¸ Ğ±Ğ°Ğ½ĞºĞ¾Ğ²ÑĞºĞ¸Ğµ ÑÑ‡ĞµÑ‚Ğ°.
ğŸ”® â”‹ ĞŸÑĞ¸Ğ¾Ğ½Ğ¸ĞºĞ¸ â€” Ğ¾Ñ‚ĞºÑ€Ğ¾Ğ¹Ñ‚Ğµ Ğ²Ğ¾Ğ·Ğ¼Ğ¾Ğ¶Ğ½Ğ¾ÑÑ‚Ğ¸ Ğ´Ğ»Ñ Ğ²Ğ°ÑˆĞµĞ³Ğ¾ Ğ¿ĞµÑ€ÑĞ¾Ğ½Ğ°Ğ¶Ğ° Ğ¸ Ğ¸ÑĞ¿Ğ¾Ğ»ÑŒĞ·ÑƒĞ¹Ñ‚Ğµ Ğ¸Ñ… Ñ ÑƒĞ¼Ğ¾Ğ¼.
ğŸŒ± â”‹ ĞœĞ½Ğ¾Ğ¶ĞµÑÑ‚Ğ²Ğ¾ ÑƒĞ½Ğ¸ĞºĞ°Ğ»ÑŒĞ½Ñ‹Ñ… Ñ€Ğ°Ñ Ñ Ğ¾ÑĞ¾Ğ±Ñ‹Ğ¼Ğ¸ ÑĞ¿Ğ¾ÑĞ¾Ğ±Ğ½Ğ¾ÑÑ‚ÑĞ¼Ğ¸.
âœ¨ â”‹ Ğ˜ÑĞºÑƒÑÑÑ‚Ğ²ĞµĞ½Ğ½Ñ‹Ğ¹ Ğ˜Ğ½Ñ‚ĞµĞ»Ğ»ĞµĞºÑ‚, Ğ±Ğ¾Ñ€Ğ³Ğ¸ Ğ¸ ÑƒĞ½Ğ¸ĞºĞ°Ğ»ÑŒĞ½Ñ‹Ğµ Ğº Ğ½Ğ¸Ğ¼ Ğ¾ÑĞ¾Ğ±ĞµĞ½Ğ½Ğ¾ÑÑ‚Ğ¸.
â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€
ğŸ’¬ ã€ŒĞŸĞ¾Ñ‡ĞµĞ¼Ñƒ Ğ²Ñ‹Ğ±Ñ€Ğ°Ñ‚ÑŒ Ğ¸Ğ¼ĞµĞ½Ğ½Ğ¾ Ğ½Ğ°Ñ?ã€ ğŸ“š
â™  â• ĞĞ°ÑˆĞ° Ğ¾Ñ‚Ğ·Ñ‹Ğ²Ñ‡Ğ¸Ğ²Ğ°Ñ Ğ°Ğ´Ğ¼Ğ¸Ğ½Ğ¸ÑÑ‚Ñ€Ğ°Ñ†Ğ¸Ñ Ğ²ÑĞµĞ³Ğ´Ğ° Ğ³Ğ¾Ñ‚Ğ¾Ğ²Ğ° Ğ¿Ğ¾Ğ¼Ğ¾Ñ‡ÑŒ Ğ²Ğ°Ğ¼ Ğ¾ÑĞ²Ğ¾Ğ¸Ñ‚ÑŒÑÑ.
â™¥ â• ĞœÑ‹ Ğ¿Ğ¾ÑÑ‚Ğ¾ÑĞ½Ğ½Ğ¾ Ñ€Ğ°Ğ±Ğ¾Ñ‚Ğ°ĞµĞ¼ Ğ½Ğ°Ğ´ ÑƒĞ»ÑƒÑ‡ÑˆĞµĞ½Ğ¸ĞµĞ¼ Ğ¸Ğ³Ñ€Ğ¾Ğ²Ğ¾Ğ³Ğ¾ Ğ¿Ñ€Ğ¾Ñ†ĞµÑÑĞ° Ğ¸ ÑĞ¾Ğ·Ğ´Ğ°ĞµĞ¼ ÑƒĞ´Ğ¾Ğ±Ğ½Ñ‹Ğµ QoL Ğ½Ğ°Ñ€Ğ°Ğ±Ğ¾Ñ‚ĞºĞ¸.
â™£ â• ĞœÑ‹ ÑÑ‚Ñ€ĞµĞ¼Ğ¸Ğ¼ÑÑ Ğº ÑĞ¾Ñ‚Ñ€ÑƒĞ´Ğ½Ğ¸Ñ‡ĞµÑÑ‚Ğ²Ñƒ, ĞºĞ°Ğº Ñ Ğ¸Ğ³Ñ€Ğ¾ĞºĞ°Ğ¼Ğ¸, Ñ‚Ğ°Ğº Ğ¸ Ñ Ğ´Ñ€ÑƒĞ³Ğ¸Ğ¼Ğ¸ Ğ¿Ñ€Ğ¾ĞµĞºÑ‚Ğ°Ğ¼Ğ¸.
"""
fallbackenabled = true
map_rotation = false
maxplayers = 50
soft_max_players = 40
map_pool = "SpaceCatsDefaultMapPool"
contraband_examine = false

[mapping]
autosave = false

[hub]
advertise = true
tags = "region:eu_e, lang:ru, rp:low, rp:med"
server_url = "ss14://spacecats.ru"
hub_urls = "https://hub.spacestation14.com/"

[infolinks]
bug_report = "https://discord.gg/vYFHfrdQQC"
discord  = "https://discord.gg/vYFHfrdQQC"
patreon = "https://boosty.to/spacecats"
wiki = "https://wiki.backmen.ru"

[server]
rules_file = "SpaceCatsRuleset"

[ahelp]
admin_prefix = true
admin_prefix_webhook = true

[admin]
role_ban_default_severity = "high"
new_player_threshold = 80
server_ban_use_last_details = true
new_player_join_sound = true

[atmos]
excited_groups = false
monstermos_equalization = false

[shuttle]
arrivals = true
arrivals_map = "/Maps/Misc/kosmoport.yml"
arrivals_returns = true
auto_call_time = 150
auto_call_extension_time = 70
emergency_dock_time = 280
emergency_authorize_time = 30
emergency_early_launch_allowed = true
arrivals_planet = false

[ic]
flavor_text = true

[chat]
rate_limit_count = 5

[vote]
map_autovote_enabled = true
preset_autovote_enabled = true
restart_not_allowed_when_admin_online = false
restart_max_players = 50
preset_enabled = false
map_enabled = false
restart_ghost_percentage = 40
restart_required_ratio = 0.7
same_type_timeout = 240
timermap = 40
timerrestart = 60
timerpreset = 30
timeralone = 30
